using System.Globalization;
using System.Windows;
using System.Windows.Controls;
using WachauEtappe.Zentrale.Models;
using WachauEtappe.Zentrale.Services;

namespace WachauEtappe.Zentrale;

public partial class TripManagementWindow : Window
{
    private TripRecord? selected;
    public TripManagementWindow(){InitializeComponent();Loaded+=(_,_)=>LoadTrips();}
    private void LoadTrips(){TripList.ItemsSource=App.Database.GetTrips();}
    private void NewTrip_Click(object sender,RoutedEventArgs e){selected=new TripRecord();ReferenceText.Text="Neue Reise · Referenz wird beim Speichern erzeugt";GuestBox.Text=EmailBox.Text=PhoneBox.Text="";StartDatePicker.SelectedDate=DateTime.Today;DailyKmBox.Text="18";ToleranceBox.Text="4";StartPlaceBox.Text="Krems";EndPlaceBox.Text="Krems";GuestsBox.Text="1";LuggageCheck.IsChecked=false;DaysGrid.ItemsSource=null;}
    private void TripList_SelectionChanged(object sender,SelectionChangedEventArgs e){selected=TripList.SelectedItem as TripRecord;if(selected is null)return;ReferenceText.Text=selected.Reference;GuestBox.Text=selected.GuestName;EmailBox.Text=selected.GuestEmail;PhoneBox.Text=selected.GuestPhone;if(DateTime.TryParse(selected.StartDate,out var d))StartDatePicker.SelectedDate=d;DailyKmBox.Text=selected.DailyTargetKm.ToString(CultureInfo.InvariantCulture);ToleranceBox.Text=selected.DailyToleranceKm.ToString(CultureInfo.InvariantCulture);StartPlaceBox.Text=selected.StartPlace;EndPlaceBox.Text=selected.EndPlace;GuestsBox.Text=selected.Guests.ToString();LuggageCheck.IsChecked=selected.LuggageTransfer;RefreshDays();}
    private void Apply(){if(selected is null)return;selected.GuestName=GuestBox.Text.Trim();selected.GuestEmail=EmailBox.Text.Trim();selected.GuestPhone=PhoneBox.Text.Trim();selected.StartDate=StartDatePicker.SelectedDate?.ToString("yyyy-MM-dd")??"";selected.StartPlace=StartPlaceBox.Text.Trim();selected.EndPlace=EndPlaceBox.Text.Trim();if(double.TryParse(DailyKmBox.Text.Replace(',','.'),NumberStyles.Any,CultureInfo.InvariantCulture,out var km))selected.DailyTargetKm=Math.Max(1,km);if(double.TryParse(ToleranceBox.Text.Replace(',','.'),NumberStyles.Any,CultureInfo.InvariantCulture,out var tol))selected.DailyToleranceKm=Math.Max(0,tol);if(int.TryParse(GuestsBox.Text,out var g))selected.Guests=Math.Max(1,g);selected.LuggageTransfer=LuggageCheck.IsChecked==true;}
    private void SaveTrip_Click(object sender,RoutedEventArgs e){if(selected is null)NewTrip_Click(sender,e);Apply();if(selected is null)return;App.Database.SaveTrip(selected);ReferenceText.Text=selected.Reference;StatusText.Text="✓ Reise gespeichert und protokolliert.";LoadTrips();}
    private void AutoPlan_Click(object sender,RoutedEventArgs e){if(selected is null)NewTrip_Click(sender,e);Apply();if(selected is null)return;try{App.Database.SaveTrip(selected);var stages=new RoutePlannerService().Plan(selected);App.Database.ReplaceTripDays(selected.Id,stages,selected.LuggageTransfer);RefreshDays();var gaps=stages.Count(s=>s.CoverageGap);StatusText.Text=gaps==0?$"✓ Tour automatisch geplant: {stages.Count} Reisetage. Für alle Übernachtungsorte wurde ein aktuell buchbarer Gastgeber gefunden.":$"⚠ Tour geplant: {stages.Count} Reisetage, davon {gaps} ohne aktuell verfügbaren freigegebenen Gastgeber.";LoadTrips();}catch(Exception ex){MessageBox.Show(ex.Message,"Tourplanung",MessageBoxButton.OK,MessageBoxImage.Warning);}}
    private void RequestAllBookings_Click(object sender,RoutedEventArgs e){if(selected is null){MessageBox.Show("Bitte zuerst eine Reise auswählen oder anlegen.");return;}Apply();App.Database.SaveTrip(selected);var result=App.Database.CreateBookingsForTrip(selected);RefreshDays();StatusText.Text=$"Unterkunftsanfragen: {result.Created} neu angelegt, {result.Skipped} übersprungen, {result.Failed} ohne freies Kontingent/Fehler.";}
    private void RefreshDays(){if(selected is null)return;DaysGrid.ItemsSource=App.Database.GetTripDays(selected.Id);}
    private void AddDay_Click(object sender,RoutedEventArgs e){if(selected is null){MessageBox.Show("Bitte zuerst eine Reise anlegen.");return;}Apply();App.Database.SaveTrip(selected);var days=App.Database.GetTripDays(selected.Id);var n=days.Count+1;var date=(StartDatePicker.SelectedDate??DateTime.Today).AddDays(n-1).ToString("yyyy-MM-dd");App.Database.AddTripDay(selected.Id,n,date,days.LastOrDefault()?.ToPlace??selected.StartPlace,"Übernachtungsort",selected.DailyTargetKm,null,selected.LuggageTransfer);RefreshDays();StatusText.Text="Manuelle Etappe angelegt.";}
    private TripDayRecord? CurrentDay()=>DaysGrid.SelectedItem as TripDayRecord;
    private void ConfirmDay_Click(object sender,RoutedEventArgs e){var d=CurrentDay();if(d is null)return;if(string.IsNullOrWhiteSpace(d.HostId)){MessageBox.Show("Diese Etappe hat noch keinen freigegebenen Gastgeber.");return;}App.Database.SetTripDayStatus(d.Id,"confirmed",d.LuggageStatus);RefreshDays();StatusText.Text="✓ Übernachtung bestätigt.";}
    private void ConfirmLuggage_Click(object sender,RoutedEventArgs e){var d=CurrentDay();if(d is null)return;if(string.IsNullOrWhiteSpace(d.HostId)){MessageBox.Show("Gepäck kann erst bestätigt werden, wenn ein Gastgeber zugeordnet ist.");return;}App.Database.SetTripDayStatus(d.Id,d.BookingStatus,"confirmed");RefreshDays();StatusText.Text="✓ Gepäckübergabe bestätigt.";}
    private void Cancel_Click(object sender,RoutedEventArgs e){if(selected is null)return;var d=CurrentDay();App.Database.RequestCancellation(selected.Id,d?.Id,0,"Gebühr manuell/rechtlich prüfen; keine automatische Abbuchung.");StatusText.Text="Storno erfasst. Keine automatische Abbuchung.";}
}
