const API=(window.WACHAUETAPPE_API_BASE||'https://web-production-907d68.up.railway.app').replace(/\/$/,'');
const $=id=>document.getElementById(id);let token=localStorage.getItem('we_partner_token')||'';
function iso(d){return d.toISOString().slice(0,10)}
function auth(){return token?{'Authorization':`Bearer ${token}`}:{}}
async function api(path,opts={}){const r=await fetch(`${API}${path}`,{...opts,headers:{'Content-Type':'application/json',...auth(),...(opts.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||data.detail||`HTTP ${r.status}`);return data}
function showPortal(on){$('loginView').hidden=on;$('portalView').hidden=!on;$('logoutBtn').hidden=!on}
async function login(e){e.preventDefault();$('loginStatus').textContent='Anmeldung läuft …';try{const data=await api('/api/partner/login',{method:'POST',body:JSON.stringify({hostId:$('hostId').value.trim(),password:$('password').value})});token=data.token;localStorage.setItem('we_partner_token',token);$('loginStatus').textContent='';await loadPortal()}catch(err){$('loginStatus').textContent=`Fehler: ${err.message}`}}
async function loadPortal(){try{const me=await api('/api/partner/me');$('hostName').textContent=me.name||me.hostId;$('hostLocation').textContent=me.location||'';showPortal(true);await Promise.all([loadAvailability(),loadCalendarStatus()])}catch(err){logout();$('loginStatus').textContent='Bitte erneut anmelden.'}}
async function loadAvailability(){const from=new Date(),to=new Date();to.setDate(to.getDate()+60);const data=await api(`/api/partner/availability?from=${iso(from)}&to=${iso(to)}`);$('availabilityRows').innerHTML=(data.rows||[]).map(r=>`<tr><td>${r.stayDate}</td><td>${r.status==='free'?'frei':r.status==='full'?'belegt':'geschlossen'}</td><td>${r.roomsFree}</td><td>${r.price!=null?'€ '+Number(r.price).toFixed(2):'–'}</td><td>${r.breakfastMode==='included'?'inklusive':r.breakfastMode==='extra'?`+ € ${Number(r.breakfastPrice||0).toFixed(2)}`:'nein'}</td><td>${r.luggageAvailable?'ja':'nein'}</td><td>${r.bookingBlocked?'Booking.com':'WachauEtappe'}</td></tr>`).join('')||'<tr><td colspan="7">Noch keine Verfügbarkeiten eingetragen.</td></tr>'}
async function saveAvailability(e){e.preventDefault();$('saveStatus').textContent='Wird gespeichert …';try{const payload={fromDate:$('fromDate').value,toDate:$('toDate').value,status:$('status').value,roomsFree:Number($('roomsFree').value||0),price:Number($('price').value||0),breakfastMode:$('breakfastMode').value,breakfastPrice:Number($('breakfastPrice').value||0),luggageAvailable:$('luggage').checked};const data=await api('/api/partner/availability/range',{method:'PUT',body:JSON.stringify(payload)});$('saveStatus').textContent=`✓ ${data.updated} Tag(e) gespeichert.`;await loadAvailability()}catch(err){$('saveStatus').textContent=`Fehler: ${err.message}`}}
async function loadCalendarStatus(){try{const data=await api('/api/partner/calendar');if(!data.connected){$('calendarBadge').textContent='nicht verbunden';$('calendarStatus').textContent='Noch kein Booking.com-Kalender verbunden.';$('bookingIcalUrl').value='';return}$('calendarBadge').textContent='verbunden';$('bookingIcalUrl').value=data.icalUrl||'';$('calendarStatus').textContent=data.lastStatus==='ok'?`✓ Letzte Synchronisierung: ${data.lastSyncAt||'–'} · ${data.blockedNights||0} zukünftige belegte Nacht/Nächte gesperrt.`:`Verbindung vorhanden. Letzter Status: ${data.lastStatus||'nicht synchronisiert'}${data.lastError?` · ${data.lastError}`:''}`}catch(err){$('calendarStatus').textContent=`Fehler: ${err.message}`}}
async function connectCalendar(e){e.preventDefault();$('calendarStatus').textContent='Booking.com-Kalender wird verbunden und synchronisiert …';try{const data=await api('/api/partner/calendar',{method:'PUT',body:JSON.stringify({icalUrl:$('bookingIcalUrl').value.trim()})});$('calendarStatus').textContent=`✓ Kalender verbunden. ${data.blockedNights||0} belegte Nacht/Nächte übernommen.`;await Promise.all([loadCalendarStatus(),loadAvailability()])}catch(err){$('calendarStatus').textContent=`Fehler: ${err.message}`}}
async function syncCalendar(){$('calendarStatus').textContent='Synchronisierung läuft …';try{const data=await api('/api/partner/calendar/sync',{method:'POST',body:'{}'});$('calendarStatus').textContent=`✓ ${data.blockedNights||0} belegte Nacht/Nächte aktualisiert.`;await Promise.all([loadCalendarStatus(),loadAvailability()])}catch(err){$('calendarStatus').textContent=`Fehler: ${err.message}`}}
async function disconnectCalendar(){if(!confirm('Booking.com-Kalender wirklich trennen? Importierte Sperren werden entfernt.'))return;try{await api('/api/partner/calendar/disconnect',{method:'POST',body:'{}'});$('calendarStatus').textContent='✓ Booking.com-Kalender getrennt.';await Promise.all([loadCalendarStatus(),loadAvailability()])}catch(err){$('calendarStatus').textContent=`Fehler: ${err.message}`}}
function logout(){token='';localStorage.removeItem('we_partner_token');showPortal(false)}
$('loginForm').addEventListener('submit',login);$('availabilityForm').addEventListener('submit',saveAvailability);$('calendarForm').addEventListener('submit',connectCalendar);$('calendarSyncBtn').addEventListener('click',syncCalendar);$('calendarDisconnectBtn').addEventListener('click',disconnectCalendar);$('logoutBtn').addEventListener('click',logout);$('refreshBtn').addEventListener('click',loadAvailability);
const t=new Date(),t2=new Date();t2.setDate(t2.getDate()+6);$('fromDate').value=iso(t);$('toDate').value=iso(t2);if(token)loadPortal();else showPortal(false);