import { Agent, routeAgentRequest } from 'agents';
import { DailyPlanner } from '../../src/daily-planner.js';
import { availabilitySignals } from '../../src/adapters/booking.js';
import { windisSignals, WINDIS_PARTNER_SEED, WINDIS_KPI_SEED } from '../../src/adapters/windis.js';
import { buildDailyNotification, mergeNotifications } from '../../src/notifications.js';
import { rankEconomicActions } from '../../src/economics.js';
import { buildOutcome, summarizeOutcomes } from '../../src/outcomes.js';
import { applyLearning, buildLearningProfile } from '../../src/learning.js';
import { buildExecution, executeApprovedAction, deliverNotification } from '../../src/execution.js';

const DAILY_CRON = '0 7 * * *';
const json = (body, status = 200) => Response.json(body, { status, headers: { 'Cache-Control': 'no-store' } });
const authorized = (request, env) => Boolean(env.ADMIN_TOKEN) && request.headers.get('Authorization') === `Bearer ${env.ADMIN_TOKEN}`;
const n = (v) => Number.isFinite(Number(v)) ? Number(v) : 0;
const pct = (v, fallback = 0) => Math.max(0, Math.min(1, Number.isFinite(Number(v)) ? Number(v) : fallback));

function economicContexts(assumptions = {}, lastResult = null) {
  const z = lastResult?.zuhauseSignals || {};
  const w = lastResult?.windisSignals || {};
  const openNights = Math.max(0, n(z.openNights));
  const zabP = pct(assumptions.zabSuccessProbability, 0);
  const zabPotentialRevenue = openNights * Math.max(0, n(assumptions.zabRevenuePerNight));
  const zabExpectedVariableCost = openNights * Math.max(0, n(assumptions.zabVariableCostPerNight)) * zabP;
  const zabCampaignCost = Math.max(0, n(assumptions.zabCampaignCost));
  const windisP = pct(assumptions.windisSuccessProbability, 0);
  return {
    zuhause_am_bach: {
      expectedRevenue: zabPotentialRevenue,
      expectedCost: zabCampaignCost + zabExpectedVariableCost,
      successProbability: zabP,
      assumptionsComplete: openNights > 0 && n(assumptions.zabRevenuePerNight) > 0 && zabP > 0,
      openNights,
      potentialRevenue: zabPotentialRevenue,
      variableCostPerNight: n(assumptions.zabVariableCostPerNight),
      campaignCost: zabCampaignCost,
    },
    windis: {
      expectedRevenue: Math.max(0, n(assumptions.windisPartnerValue)),
      expectedCost: Math.max(0, n(assumptions.windisOutreachCost)),
      successProbability: windisP,
      assumptionsComplete: n(assumptions.windisPartnerValue) > 0 && windisP > 0,
      openPartnerActions: n(w.openPartnerActions),
      priorityAOpen: n(w.priorityAOpen),
    },
  };
}

function cockpitHtml(){return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Growth Cockpit</title><style>
:root{font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif;color:#17211b;background:#f3f5f3}*{box-sizing:border-box}body{max-width:1240px;margin:0 auto;padding:28px 18px 60px}h1{font-size:34px;margin:0 0 6px}h2{margin-top:30px}.sub{color:#627067;margin-bottom:22px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.card{background:#fff;border:1px solid #dce2dd;border-radius:14px;padding:16px;margin:10px 0;box-shadow:0 1px 2px rgba(0,0,0,.03)}.metric{font-size:28px;font-weight:750;margin-top:3px}.muted{color:#6d7870}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.label{font-size:13px;font-weight:700;color:#5f6b62;text-transform:uppercase;letter-spacing:.04em}.brand{font-size:18px;font-weight:800}.pill{display:inline-block;border-radius:999px;padding:5px 10px;font-size:13px;font-weight:750}.green{background:#e5f7ea;color:#17612e}.yellow{background:#fff4d6;color:#765200}.red{background:#fde8e7;color:#8a241e}.gray{background:#eef1ef;color:#59625d}.section{border-top:1px solid #e4e8e5;margin-top:14px;padding-top:14px}input,textarea,button{font:inherit}input,textarea{width:100%;padding:10px 11px;border:1px solid #cfd6d1;border-radius:8px;background:white}textarea{min-height:65px}button{padding:10px 14px;border:1px solid #bfc8c1;border-radius:8px;background:white;cursor:pointer;font-weight:650}button.primary{background:#183d2a;color:white;border-color:#183d2a}button.danger{color:#8a241e}.top-controls{display:grid;grid-template-columns:2fr 2fr auto;gap:10px;align-items:end}.warnbox{background:#fff7e6;border:1px solid #ead19b;border-radius:10px;padding:10px 12px;margin:7px 0}.channel-ok{color:#17612e}.channel-off{color:#8a241e}.money{font-variant-numeric:tabular-nums}.assumptions{background:#fbfcfb}.help{font-size:13px;color:#6d7870}.recommend{font-size:20px;font-weight:850}.kpis{margin-top:10px}.execution-ok{color:#17612e;font-weight:700}.execution-blocked{color:#8a5a00;font-weight:700}@media(max-width:800px){.top-controls{grid-template-columns:1fr}body{padding:18px 12px}}
</style></head><body><h1>Growth Cockpit</h1><div class="sub">Zuhause am Bach + Wilde Wachauer Windis · wirtschaftlicher Erfolg als Hauptmaß: erkennen → bewerten → entscheiden → durchführen → messen → lernen.</div>
<div class="top-controls"><div><div class="label">Agent-Basis-URL</div><input id="base" placeholder="https://.../agents/growth-runtime/main"></div><div><div class="label">ADMIN_TOKEN</div><input id="token" type="password"></div><div class="row"><button class="primary" onclick="load()">Cockpit laden</button><button onclick="runNow()">Analyse ausführen</button></div></div>
<div id="summary"></div><div id="warnings"></div>
<h2>Wirtschaftliche Annahmen</h2><div class="card assumptions"><div class="help">Diese Werte sind deine steuerbaren Annahmen. Ohne belastbare Werte zeigt das Cockpit keine erfundene Empfehlung. Werte werden im Growth-Agent gespeichert.</div><div class="grid kpis"><div><div class="label">ZaB Umsatz pro zusätzlicher Nacht (€)</div><input id="a-zabRev" type="number" min="0" step="1"></div><div><div class="label">ZaB variable Kosten pro Nacht (€)</div><input id="a-zabVar" type="number" min="0" step="1"></div><div><div class="label">ZaB Kosten je Kampagne (€)</div><input id="a-zabCost" type="number" min="0" step="1"></div><div><div class="label">ZaB Erfolgswahrscheinlichkeit (%)</div><input id="a-zabProb" type="number" min="0" max="100" step="1"></div><div><div class="label">Windis Wert erfolgreicher Partneraktion (€)</div><input id="a-winVal" type="number" min="0" step="1"></div><div><div class="label">Windis Kosten je Outreach (€)</div><input id="a-winCost" type="number" min="0" step="1"></div><div><div class="label">Windis Erfolgswahrscheinlichkeit (%)</div><input id="a-winProb" type="number" min="0" max="100" step="1"></div></div><button class="primary" onclick="saveAssumptions()">Annahmen speichern & neu bewerten</button></div>
<h2>Priorisierte Entscheidungen</h2><div id="decisions"></div>
<h2>Durchführung</h2><div id="executions"></div>
<h2>Erfolgsmessung</h2><div id="measure"></div>
<h2>Lernen & Wirtschaftserfolg</h2><div id="learning"></div>
<script>
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c])),auth=()=>({'Authorization':'Bearer '+$('token').value,'Content-Type':'application/json'});let latest=null;
async function req(p,o={}){const r=await fetch($('base').value.replace(/\\/$/,'')+p,{...o,headers:{...auth(),...(o.headers||{})}}),j=await r.json();if(!r.ok)throw new Error(j.error||r.status);return j}
const euro=v=>Number.isFinite(Number(v))?new Intl.NumberFormat('de-AT',{style:'currency',currency:'EUR'}).format(Number(v)):'—';
const brandName=b=>b==='zuhause_am_bach'?'Zuhause am Bach':b==='windis'?'Wilde Wachauer Windis':b;
const actionName=k=>({publish:'Veröffentlichung',sendExternalMessage:'Partner-Outreach',spendMoney:'Werbeausgabe'})[k]||k;
const actionText=k=>k==='publish'?'Nach deiner Freigabe wird die vorbereitete Veröffentlichung an den verbundenen Publishing-Kanal übergeben. Ist kein Kanal verbunden, bleibt die Aktion sicher blockiert.':k==='sendExternalMessage'?'Nach deiner Freigabe wird die personalisierte Partnernachricht an den verbundenen Outreach-Kanal übergeben. Ohne verbundenen Kanal erfolgt kein Versand.':'Nach Freigabe wird die Aktion nur über einen konfigurierten Ausführungskanal ausgeführt.';
function recommendation(a){const e=a.economics||{},ctx=a.context||{};if(!ctx.assumptionsComplete)return{c:'gray',t:'Annahmen ergänzen',why:'Für eine belastbare Empfehlung fehlen wirtschaftliche Annahmen.'};if(e.expectedContribution>0)return{c:'green',t:'Freigeben empfohlen',why:'Der erwartete wirtschaftliche Beitrag ist positiv.'};if(e.expectedContribution<0)return{c:'red',t:'Nicht freigeben empfohlen',why:'Die erwarteten Kosten übersteigen den risikogewichteten Nutzen.'};return{c:'yellow',t:'Manuell prüfen',why:'Erwarteter wirtschaftlicher Beitrag ist neutral.'}}
function fillAssumptions(a={}){$('a-zabRev').value=a.zabRevenuePerNight??'';$('a-zabVar').value=a.zabVariableCostPerNight??'';$('a-zabCost').value=a.zabCampaignCost??'';$('a-zabProb').value=a.zabSuccessProbability!=null?Math.round(a.zabSuccessProbability*100):'';$('a-winVal').value=a.windisPartnerValue??'';$('a-winCost').value=a.windisOutreachCost??'';$('a-winProb').value=a.windisSuccessProbability!=null?Math.round(a.windisSuccessProbability*100):''}
function render(s){latest=s;fillAssumptions(s.assumptions||{});const o=s.outcomeSummary||{},z=s.lastResult?.zuhauseSignals||{},ch=s.channels||{};$('summary').innerHTML='<div class="grid"><div class="card"><div class="label">Freie Nächte · 30 Tage</div><div class="metric">'+esc(z.openNights??'—')+'</div></div><div class="card"><div class="label">Offene Entscheidungen</div><div class="metric">'+(s.approvals||[]).length+'</div></div><div class="card"><div class="label">Gemessener Umsatz</div><div class="metric money">'+euro(o.totalRevenue)+'</div></div><div class="card"><div class="label">Deckungsbeitrag Maßnahmen</div><div class="metric money">'+euro(o.totalContribution)+'</div></div><div class="card"><div class="label">Ausführungskanäle</div><div>Publishing: <b class="'+(ch.publish?'channel-ok':'channel-off')+'">'+(ch.publish?'verbunden':'nicht verbunden')+'</b><br>Outreach: <b class="'+(ch.outreach?'channel-ok':'channel-off')+'">'+(ch.outreach?'verbunden':'nicht verbunden')+'</b><br>Benachrichtigung: <b class="'+(ch.notifications?'channel-ok':'channel-off')+'">'+(ch.notifications?'verbunden':'nicht verbunden')+'</b></div></div></div>';
$('warnings').innerHTML=(s.warnings||[]).length?'<h2>Warnungen</h2>'+(s.warnings||[]).map(w=>'<div class="warnbox">⚠ '+esc(w)+'</div>').join(''):'';
$('decisions').innerHTML=(s.decisions||[]).map(a=>{const r=recommendation(a),e=a.economics||{},ctx=a.context||{};return '<div class="card"><div class="row"><span class="brand">'+esc(brandName(a.brand))+'</span><span class="pill '+r.c+'">'+r.t+'</span><span class="pill gray">'+esc(actionName(a.kind))+'</span></div><p><b>Vorgeschlagene Aktion:</b> '+esc(a.task)+'</p><div class="grid"><div><div class="label">Potenzial / erwarteter Umsatz</div><div class="metric money">'+euro(e.expectedRevenue)+'</div></div><div><div class="label">Erwartete Kosten</div><div class="metric money">'+euro(e.expectedCost)+'</div></div><div><div class="label">Erwarteter Deckungsbeitrag</div><div class="metric money">'+euro(e.expectedContribution)+'</div></div><div><div class="label">Erfolgswahrscheinlichkeit</div><div class="metric">'+Math.round((e.successProbability||0)*100)+'%</div></div></div><div class="section"><div class="recommend">'+r.t+'</div><div>'+esc(r.why)+'</div><div class="help">Evidenz: '+esc(e.confidence||'unknown')+(ctx.openNights!=null?' · '+ctx.openNights+' freie Nächte berücksichtigt':'')+'</div></div><div class="section"><b>Was passiert nach Freigabe?</b><div class="help">'+esc(actionText(a.kind))+'</div></div><textarea id="n-'+a.id+'" placeholder="Notiz zur Entscheidung (optional)"></textarea><div class="row"><button class="primary" onclick="decide(\\''+a.id+'\\',\\'approve\\')">Freigeben</button><button class="danger" onclick="decide(\\''+a.id+'\\',\\'reject\\')">Ablehnen</button></div></div>'}).join('')||'<div class="card">Keine offenen Entscheidungen.</div>';
$('executions').innerHTML=(s.executions||[]).slice().reverse().map(x=>'<div class="card"><b>'+esc(brandName(x.brand))+' · '+esc(x.task)+'</b><p>Status: <span class="'+(x.status==='blocked'?'execution-blocked':'execution-ok')+'">'+esc(x.status)+'</span>'+(x.blockedReason?' · '+esc(x.blockedReason):'')+'</p>'+(x.status==='blocked'?'<button onclick="retry(\\''+x.id+'\\')">Erneut ausführen</button>':'')+'</div>').join('')||'<div class="card">Noch keine Durchführungen.</div>';
$('measure').innerHTML=(s.approvedAwaitingOutcome||[]).map(a=>'<div class="card"><b>'+esc(brandName(a.brand))+' · '+esc(a.task)+'</b><div class="grid"><div><div class="label">Tatsächlicher Umsatz (€)</div><input id="r-'+a.id+'" type="number" min="0" step="0.01"></div><div><div class="label">Tatsächliche Kosten (€)</div><input id="c-'+a.id+'" type="number" min="0" step="0.01"></div></div><textarea id="on-'+a.id+'" placeholder="Ergebnis / Beobachtung"></textarea><button class="primary" onclick="measure(\\''+a.id+'\\')">Ergebnis verbuchen</button></div>').join('')||'<div class="card">Keine freigegebene Maßnahme wartet auf Erfolgsmessung.</div>';
$('learning').innerHTML='<div class="grid"><div class="card"><div class="label">Gemessene Maßnahmen</div><div class="metric">'+(o.measuredActions||0)+'</div></div><div class="card"><div class="label">Profitabel</div><div class="metric">'+(o.profitableActions||0)+'</div></div><div class="card"><div class="label">Verlustbringend</div><div class="metric">'+(o.lossMakingActions||0)+'</div></div><div class="card"><div class="label">Gesamt-ROI</div><div class="metric">'+(o.roi==null?'—':Math.round(o.roi*100)+'%')+'</div></div></div><div class="card help">Mit jeder verbuchten Maßnahme aktualisiert die Lernlogik ihre Erfolgsannahmen. Gemessener wirtschaftlicher Erfolg hat Vorrang vor Reichweite, Likes oder Klicks.</div>'}
async function load(){try{render(await req('/status'))}catch(e){alert(e.message)}}async function runNow(){try{await req('/run-now',{method:'POST'});await load()}catch(e){alert(e.message)}}async function saveAssumptions(){try{await req('/assumptions',{method:'POST',body:JSON.stringify({zabRevenuePerNight:Number($('a-zabRev').value||0),zabVariableCostPerNight:Number($('a-zabVar').value||0),zabCampaignCost:Number($('a-zabCost').value||0),zabSuccessProbability:Number($('a-zabProb').value||0)/100,windisPartnerValue:Number($('a-winVal').value||0),windisOutreachCost:Number($('a-winCost').value||0),windisSuccessProbability:Number($('a-winProb').value||0)/100})});await load()}catch(e){alert(e.message)}}async function decide(id,k){try{await req('/'+k,{method:'POST',body:JSON.stringify({id,note:$('n-'+id).value})});await load()}catch(e){alert(e.message)}}async function retry(id){try{await req('/execute',{method:'POST',body:JSON.stringify({executionId:id})});await load()}catch(e){alert(e.message)}}async function measure(id){try{await req('/outcomes',{method:'POST',body:JSON.stringify({approvalId:id,actualRevenue:Number($('r-'+id).value||0),actualCost:Number($('c-'+id).value||0),note:$('on-'+id).value})});await load()}catch(e){alert(e.message)}}
</script></body></html>`}

function mergeApprovals(existing,incoming){const result=[...existing];for(const item of incoming)if(!result.some(e=>e.status==='pending'&&e.brand===item.brand&&e.kind===item.kind&&e.task===item.task))result.push(item);return result.slice(-200)}

export class GrowthRuntime extends Agent{
 initialState={lastRunAt:null,lastResult:null,approvals:[],notifications:[],warnings:[],outcomes:[],executions:[],assumptions:{zabRevenuePerNight:0,zabVariableCostPerNight:0,zabCampaignCost:0,zabSuccessProbability:0,windisPartnerValue:0,windisOutreachCost:0,windisSuccessProbability:0}};
 async onStart(){const schedules=await this.listSchedules({type:'cron'});if(!schedules.some(s=>s.callback==='dailyRun'&&s.cron===DAILY_CRON))await this.schedule(DAILY_CRON,'dailyRun',{source:'scheduler'})}
 async loadZuhauseSignals(w){if(!this.env.BOOKING_WORKER_URL){w.push('BOOKING_WORKER_URL ist nicht konfiguriert');return{openNights:0,source:'missing'}}const r=await fetch(this.env.BOOKING_WORKER_URL,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`Booking worker HTTP ${r.status}`);return availabilitySignals(await r.json(),{horizonDays:30})}
 async loadWindisSignals(w){if(!this.env.WINDIS_DATA_URL){w.push('WINDIS_DATA_URL nicht konfiguriert; geprüfte Repository-Seed-Daten werden verwendet');return windisSignals({partners:WINDIS_PARTNER_SEED,kpis:WINDIS_KPI_SEED})}const r=await fetch(this.env.WINDIS_DATA_URL,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`Windis data HTTP ${r.status}`);return windisSignals(await r.json())}
 async dailyRun(payload={source:'manual'}){const warnings=[],planner=new DailyPlanner();let zuhauseSignals;try{zuhauseSignals=await this.loadZuhauseSignals(warnings)}catch(e){warnings.push(`Zuhause-Datenfehler: ${e?.message||String(e)}`);zuhauseSignals={openNights:0,source:'error'}}let windisSignalsValue;try{windisSignalsValue=await this.loadWindisSignals(warnings)}catch(e){warnings.push(`Windis-Datenfehler: ${e?.message||String(e)}`);windisSignalsValue=windisSignals({partners:WINDIS_PARTNER_SEED,kpis:WINDIS_KPI_SEED})}const result=planner.buildDay({zuhauseSignals,windisSignals:windisSignalsValue}),approvals=mergeApprovals(this.state.approvals||[],result.approvalsPending||[]),notification=buildDailyNotification({zuhauseSignals,windisSignals:windisSignalsValue,execution:result.execution,approvals,warnings});const delivery=await deliverNotification(notification,this.env);const notifications=mergeNotifications(this.state.notifications||[],[{...notification,delivery}]);const next={...this.state,lastRunAt:new Date().toISOString(),lastResult:{source:payload?.source||'unknown',zuhauseSignals,windisSignals:windisSignalsValue,execution:result.execution},approvals,notifications,warnings,outcomes:this.state.outcomes||[],executions:this.state.executions||[],assumptions:this.state.assumptions||this.initialState.assumptions};this.setState(next);return{...next.lastResult,notification:{...notification,delivery}}}
 setAssumptions(body={}){const clean={zabRevenuePerNight:Math.max(0,n(body.zabRevenuePerNight)),zabVariableCostPerNight:Math.max(0,n(body.zabVariableCostPerNight)),zabCampaignCost:Math.max(0,n(body.zabCampaignCost)),zabSuccessProbability:pct(body.zabSuccessProbability),windisPartnerValue:Math.max(0,n(body.windisPartnerValue)),windisOutreachCost:Math.max(0,n(body.windisOutreachCost)),windisSuccessProbability:pct(body.windisSuccessProbability)};this.setState({...this.state,assumptions:clean});return clean}
 async decideApproval(id,decision,note=''){if(!['approved','rejected'].includes(decision))throw new Error('invalid_decision');const found=(this.state.approvals||[]).find(i=>i.id===id);if(!found)throw new Error('approval_not_found');if(found.status!=='pending')throw new Error('approval_already_decided');const contexts=economicContexts(this.state.assumptions||{},this.state.lastResult),context=contexts[found.brand]||{},scored=rankEconomicActions([{...found}],{[found.brand]:context})[0],decided={...found,...scored,status:decision,note,decidedAt:new Date().toISOString()},approvals=(this.state.approvals||[]).map(i=>i.id===id?decided:i);let executions=this.state.executions||[];if(decision==='approved'){let execution=buildExecution(decided);execution=await executeApprovedAction(execution,decided,this.env);executions=[...executions,execution].slice(-500)}this.setState({...this.state,approvals,executions});return decided}
 async retryExecution(id){const current=(this.state.executions||[]).find(x=>x.id===id);if(!current)throw new Error('execution_not_found');const approval=(this.state.approvals||[]).find(a=>a.id===current.approvalId);const updated=await executeApprovedAction(current,approval,this.env),executions=(this.state.executions||[]).map(x=>x.id===id?updated:x);this.setState({...this.state,executions});return updated}
 recordOutcome(body){const approval=(this.state.approvals||[]).find(i=>i.id===body.approvalId);if(!approval)throw new Error('approval_not_found');if((this.state.outcomes||[]).some(o=>o.approvalId===approval.id))throw new Error('outcome_already_recorded');const execution=(this.state.executions||[]).find(x=>x.approvalId===approval.id)||null,outcome=buildOutcome({approval,execution,actualRevenue:body.actualRevenue,actualCost:body.actualCost,note:body.note||'',source:body.source||'manual'}),outcomes=[...(this.state.outcomes||[]),outcome].slice(-500);this.setState({...this.state,outcomes});return outcome}
 async onRequest(request){const url=new URL(request.url);if(!authorized(request,this.env))return json({error:'unauthorized'},401);try{if(request.method==='GET'&&url.pathname.endsWith('/status')){const pending=(this.state.approvals||[]).filter(i=>i.status==='pending'),outcomes=this.state.outcomes||[],profile=buildLearningProfile(outcomes),contexts=economicContexts(this.state.assumptions||{},this.state.lastResult),learned=pending.map(a=>applyLearning(a,profile)),decisions=rankEconomicActions(learned,contexts).map(d=>({...d,context:contexts[d.brand]||{}})),measured=new Set(outcomes.map(o=>o.approvalId)),approvedAwaitingOutcome=(this.state.approvals||[]).filter(i=>i.status==='approved'&&!measured.has(i.id));return json({lastRunAt:this.state.lastRunAt,lastResult:this.state.lastResult,warnings:this.state.warnings||[],approvals:pending,decisions,executions:this.state.executions||[],approvedAwaitingOutcome,outcomes:outcomes.slice(-50).reverse(),outcomeSummary:summarizeOutcomes(outcomes),learningProfile:profile,assumptions:this.state.assumptions||this.initialState.assumptions,notifications:(this.state.notifications||[]).filter(i=>i.status==='pending'),channels:{publish:Boolean(this.env.PUBLISH_WEBHOOK_URL),outreach:Boolean(this.env.OUTREACH_WEBHOOK_URL),notifications:Boolean(this.env.NOTIFICATION_WEBHOOK_URL)},schedule:DAILY_CRON})}if(request.method==='POST'&&url.pathname.endsWith('/run-now'))return json(await this.dailyRun({source:'manual'}));if(request.method==='POST'&&url.pathname.endsWith('/assumptions'))return json(this.setAssumptions(await request.json()));if(request.method==='POST'&&url.pathname.endsWith('/outcomes'))return json(this.recordOutcome(await request.json()));if(request.method==='POST'&&url.pathname.endsWith('/execute')){const b=await request.json();return json(await this.retryExecution(b.executionId))}if(request.method==='POST'&&(url.pathname.endsWith('/approve')||url.pathname.endsWith('/reject'))){const b=await request.json();return json(await this.decideApproval(b.id,url.pathname.endsWith('/approve')?'approved':'rejected',b.note||''))}return json({error:'not_found'},404)}catch(e){return json({error:e?.message||String(e)},400)}}
}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/health')return json({ok:true,service:'zab-windis-growth-runtime'});if(url.pathname==='/approval-ui'||url.pathname==='/cockpit')return new Response(cockpitHtml(),{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}});return(await routeAgentRequest(request,env))||json({error:'not_found'},404)}};