from pathlib import Path

p = Path("zab-paypal-checkout.js")
s = p.read_text(encoding="utf-8")

old = '''    const checkoutLang=(new URLSearchParams(window.location.search).get("lang")||document.documentElement.lang||"de").slice(0,2).toLowerCase();
    const deCheckout=checkoutLang==="de";
    const L=(de,en)=>deCheckout?de:en;'''
new = r'''    const requestedLang=(new URLSearchParams(window.location.search).get("lang")||document.documentElement.lang||"de").slice(0,2).toLowerCase();
    const supportedCheckoutLangs=new Set(["de","en","cs","sk","hu","pl","nl"]);
    const checkoutLang=supportedCheckoutLangs.has(requestedLang)?requestedLang:"de";
    const T={
      de:{choose:"Termin wählen",hero:"Direkt buchen ohne Buchungsplattform",title:"Wachau-Etappe direkt buchen",intro:"Reisedaten wählen, Live-Verfügbarkeit prüfen und einen freien Termin sicher mit PayPal direkt buchen. Eine Kredit-/Debitkartenzahlung kann PayPal im Gast-Checkout anbieten. Falls Sofortbuchung nicht möglich ist, bleibt die persönliche Anfrage verfügbar.",trust:"Direkt buchen bei den Gastgebern",trust2:"Live-Verfügbarkeit, transparenter Preis und sichere Zahlung über PayPal – auch per Kredit- oder Debitkarte, soweit PayPal dies anbietet.",trust3:"Ohne Provision oder Umweg über eine zusätzliche Buchungsplattform.",tile:"Direkt buchen",tile2:"Verfügbarkeit live prüfen",request:"Buchungsanfrage senden",blocked:"⛔ Belegt – bitte anderen Termin wählen",blocked2:"Das Zimmer ist für diesen Zeitraum bereits belegt.",blocked3:"⛔ Belegt – bitte einen anderen Termin wählen.",checking:"Verfügbarkeit wird geprüft",checking2:"Verfügbarkeit wird direkt mit dem aktuellen Booking-Kalender geprüft …",pay:"Jetzt mit PayPal bezahlen",available:"✅ Termin frei – sichere Direktzahlung",available2:"Termin ist laut aktuellem Booking-Kalender frei. Beim Klick wird der Termin serverseitig reserviert und vor PayPal nochmals sicher geprüft. Eine Kredit-/Debitkartenzahlung kann PayPal im Gast-Checkout anbieten; die tatsächliche Verfügbarkeit bestimmt PayPal.",available3:"✅ Frei – live über den aktuellen Booking-Kalender geprüft.",config:"Sofortzahlung ist noch nicht vollständig eingerichtet. Bitte senden Sie stattdessen die Buchungsanfrage.",calendarBlock:"Der Booking-Kalender sperrt diesen Zeitraum. Bitte einen anderen Termin wählen.",luggage:"Gepäcktransport hat einen streckenabhängigen Preis. Bitte Gepäcktransport abwählen und die Übernachtung bezahlen oder zuerst eine Anfrage senden.",unreachable:"Live-Verfügbarkeitsprüfung derzeit nicht erreichbar. Bitte Buchungsanfrage senden oder später erneut versuchen.",preparing:"PayPal wird vorbereitet …",finalCheck:"Verfügbarkeit und Preis werden jetzt serverseitig final geprüft.",paypalError:"⚠️ PayPal konnte nicht gestartet werden"},
      en:{choose:"Choose dates",hero:"Book direct without another booking platform",title:"Book your Wachau stay direct",intro:"Choose your dates, check live availability and book an available stay securely via PayPal. PayPal may also offer debit or credit card payment. If instant booking is unavailable, you can still send a personal request.",trust:"Book directly with your hosts",trust2:"Live availability, transparent direct price and secure payment via PayPal; debit or credit card may also be offered by PayPal.",trust3:"No detour through another booking platform.",tile:"Book direct",tile2:"Check live availability",request:"Send booking request",blocked:"⛔ Unavailable – please choose different dates",blocked2:"The room is unavailable for these dates.",blocked3:"⛔ Unavailable – please choose different dates.",checking:"Checking availability",checking2:"Availability is being checked against the current Booking calendar …",pay:"Pay securely with PayPal",available:"✅ Available – secure direct payment",available2:"These dates are available according to the current Booking calendar. When you continue, the stay is held server-side and checked once more before PayPal. PayPal may offer debit or credit card payment in guest checkout; availability is determined by PayPal.",available3:"✅ Available – checked live against the current Booking calendar.",config:"Instant payment is not fully available right now. Please send a booking request instead.",calendarBlock:"The Booking calendar blocks these dates. Please choose different dates.",luggage:"Luggage transfer has a route-dependent price. Please deselect it to pay for the stay now, or send a request first.",unreachable:"Live availability is temporarily unavailable. Please send a booking request or try again later.",preparing:"Preparing PayPal …",finalCheck:"Availability and price are now being checked one final time on the server.",paypalError:"⚠️ PayPal could not be started"},
      cs:{choose:"Vyberte termín",hero:"Rezervujte přímo bez rezervační platformy",title:"Rezervujte si pobyt ve Wachau přímo",intro:"Vyberte termín, ověřte živou dostupnost a volný pobyt bezpečně rezervujte přes PayPal. PayPal může nabídnout také platbu debetní nebo kreditní kartou. Pokud okamžitá rezervace není možná, můžete odeslat osobní poptávku.",trust:"Rezervace přímo u hostitelů",trust2:"Živá dostupnost, transparentní přímá cena a bezpečná platba přes PayPal; PayPal může nabídnout i platbu kartou.",trust3:"Bez prostředníka a další rezervační platformy.",tile:"Rezervovat přímo",tile2:"Ověřit živou dostupnost",request:"Odeslat poptávku",blocked:"⛔ Obsazeno – vyberte jiný termín",blocked2:"Pokoj není v tomto termínu dostupný.",blocked3:"⛔ Obsazeno – vyberte jiný termín.",checking:"Ověřujeme dostupnost",checking2:"Dostupnost se ověřuje podle aktuálního kalendáře Booking …",pay:"Zaplatit bezpečně přes PayPal",available:"✅ Volno – bezpečná přímá platba",available2:"Termín je podle aktuálního kalendáře Booking volný. Před přesměrováním na PayPal je rezervace na serveru ještě jednou bezpečně ověřena. PayPal může v režimu hosta nabídnout platbu kartou.",available3:"✅ Volno – ověřeno podle aktuálního kalendáře Booking.",config:"Okamžitá platba není nyní plně dostupná. Odešlete prosím poptávku.",calendarBlock:"Kalendář Booking tento termín blokuje. Vyberte jiný termín.",luggage:"Přeprava zavazadel má cenu podle trasy. Pro okamžitou platbu ji zrušte, nebo nejprve odešlete poptávku.",unreachable:"Živou dostupnost nyní nelze ověřit. Odešlete poptávku nebo to zkuste později.",preparing:"Připravujeme PayPal …",finalCheck:"Dostupnost a cena se nyní naposledy ověřují na serveru.",paypalError:"⚠️ PayPal se nepodařilo spustit"},
      sk:{choose:"Vyberte termín",hero:"Rezervujte priamo bez rezervačnej platformy",title:"Rezervujte si pobyt vo Wachau priamo",intro:"Vyberte termín, overte živú dostupnosť a voľný pobyt bezpečne rezervujte cez PayPal. PayPal môže ponúknuť aj platbu debetnou alebo kreditnou kartou. Ak okamžitá rezervácia nie je možná, môžete odoslať osobnú požiadavku.",trust:"Rezervácia priamo u hostiteľov",trust2:"Živá dostupnosť, transparentná priama cena a bezpečná platba cez PayPal; PayPal môže ponúknuť aj platbu kartou.",trust3:"Bez sprostredkovateľa a ďalšej rezervačnej platformy.",tile:"Rezervovať priamo",tile2:"Overiť živú dostupnosť",request:"Odoslať požiadavku",blocked:"⛔ Obsadené – vyberte iný termín",blocked2:"Izba nie je v tomto termíne dostupná.",blocked3:"⛔ Obsadené – vyberte iný termín.",checking:"Overujeme dostupnosť",checking2:"Dostupnosť sa overuje podľa aktuálneho kalendára Booking …",pay:"Zaplatiť bezpečne cez PayPal",available:"✅ Voľné – bezpečná priama platba",available2:"Termín je podľa aktuálneho kalendára Booking voľný. Pred presmerovaním na PayPal sa rezervácia na serveri ešte raz bezpečne overí. PayPal môže v režime hosťa ponúknuť platbu kartou.",available3:"✅ Voľné – overené podľa aktuálneho kalendára Booking.",config:"Okamžitá platba momentálne nie je plne dostupná. Odošlite prosím požiadavku.",calendarBlock:"Kalendár Booking tento termín blokuje. Vyberte iný termín.",luggage:"Preprava batožiny má cenu podľa trasy. Pre okamžitú platbu ju zrušte alebo najprv odošlite požiadavku.",unreachable:"Živú dostupnosť teraz nemožno overiť. Odošlite požiadavku alebo to skúste neskôr.",preparing:"Pripravujeme PayPal …",finalCheck:"Dostupnosť a cena sa teraz naposledy overujú na serveri.",paypalError:"⚠️ PayPal sa nepodarilo spustiť"},
      hu:{choose:"Válasszon dátumot",hero:"Foglaljon közvetlenül foglalási platform nélkül",title:"Foglalja le közvetlenül wachaui tartózkodását",intro:"Válassza ki a dátumokat, ellenőrizze az élő elérhetőséget, és foglalja le biztonságosan a szabad időpontot PayPalon keresztül. A PayPal bank- vagy hitelkártyás fizetést is felajánlhat. Ha az azonnali foglalás nem lehetséges, személyes érdeklődést küldhet.",trust:"Foglalás közvetlenül a házigazdáknál",trust2:"Élő elérhetőség, átlátható közvetlen ár és biztonságos PayPal-fizetés; a PayPal kártyás fizetést is felajánlhat.",trust3:"Közvetítő és további foglalási platform nélkül.",tile:"Közvetlen foglalás",tile2:"Élő elérhetőség ellenőrzése",request:"Foglalási érdeklődés küldése",blocked:"⛔ Foglalt – válasszon másik dátumot",blocked2:"A szoba ezekre a dátumokra nem elérhető.",blocked3:"⛔ Foglalt – válasszon másik dátumot.",checking:"Elérhetőség ellenőrzése",checking2:"Az elérhetőséget az aktuális Booking-naptár alapján ellenőrizzük …",pay:"Biztonságos fizetés PayPallal",available:"✅ Szabad – biztonságos közvetlen fizetés",available2:"A dátum az aktuális Booking-naptár szerint szabad. A PayPalra irányítás előtt a foglalást a szerver még egyszer ellenőrzi. A PayPal vendégként kártyás fizetést is felajánlhat.",available3:"✅ Szabad – az aktuális Booking-naptár alapján ellenőrizve.",config:"Az azonnali fizetés jelenleg nem teljesen elérhető. Küldjön inkább foglalási érdeklődést.",calendarBlock:"A Booking-naptár blokkolja ezt az időpontot. Válasszon másik dátumot.",luggage:"A csomagszállítás ára útvonalfüggő. Az azonnali fizetéshez törölje ezt az opciót, vagy előbb küldjön érdeklődést.",unreachable:"Az élő elérhetőség jelenleg nem ellenőrizhető. Küldjön érdeklődést vagy próbálja később.",preparing:"PayPal előkészítése …",finalCheck:"Az elérhetőséget és az árat a szerver most még egyszer véglegesen ellenőrzi.",paypalError:"⚠️ A PayPal nem indítható"},
      pl:{choose:"Wybierz termin",hero:"Rezerwuj bezpośrednio bez platformy rezerwacyjnej",title:"Zarezerwuj pobyt w Wachau bezpośrednio",intro:"Wybierz termin, sprawdź dostępność na żywo i bezpiecznie zarezerwuj wolny pobyt przez PayPal. PayPal może również zaoferować płatność kartą debetową lub kredytową. Jeśli rezerwacja natychmiastowa nie jest możliwa, możesz wysłać zapytanie.",trust:"Rezerwacja bezpośrednio u gospodarzy",trust2:"Dostępność na żywo, przejrzysta cena bezpośrednia i bezpieczna płatność przez PayPal; PayPal może także zaoferować płatność kartą.",trust3:"Bez pośrednika i dodatkowej platformy rezerwacyjnej.",tile:"Rezerwuj bezpośrednio",tile2:"Sprawdź dostępność na żywo",request:"Wyślij zapytanie",blocked:"⛔ Zajęte – wybierz inny termin",blocked2:"Pokój nie jest dostępny w tym terminie.",blocked3:"⛔ Zajęte – wybierz inny termin.",checking:"Sprawdzamy dostępność",checking2:"Dostępność jest sprawdzana w aktualnym kalendarzu Booking …",pay:"Zapłać bezpiecznie przez PayPal",available:"✅ Wolne – bezpieczna płatność bezpośrednia",available2:"Termin jest wolny według aktualnego kalendarza Booking. Przed przejściem do PayPal rezerwacja jest ponownie bezpiecznie sprawdzana na serwerze. PayPal może w trybie gościa zaoferować płatność kartą.",available3:"✅ Wolne – sprawdzone w aktualnym kalendarzu Booking.",config:"Płatność natychmiastowa nie jest obecnie w pełni dostępna. Wyślij zapytanie.",calendarBlock:"Kalendarz Booking blokuje ten termin. Wybierz inny termin.",luggage:"Transport bagażu ma cenę zależną od trasy. Aby zapłacić od razu, odznacz tę opcję lub najpierw wyślij zapytanie.",unreachable:"Nie można teraz sprawdzić dostępności na żywo. Wyślij zapytanie lub spróbuj później.",preparing:"Przygotowujemy PayPal …",finalCheck:"Dostępność i cena są teraz ostatecznie sprawdzane na serwerze.",paypalError:"⚠️ Nie udało się uruchomić PayPal"},
      nl:{choose:"Kies data",hero:"Boek rechtstreeks zonder boekingsplatform",title:"Boek uw verblijf in de Wachau rechtstreeks",intro:"Kies uw data, controleer de live beschikbaarheid en boek een vrij verblijf veilig via PayPal. PayPal kan ook betaling met een betaalpas of creditcard aanbieden. Als direct boeken niet mogelijk is, kunt u een persoonlijke aanvraag sturen.",trust:"Boek rechtstreeks bij de hosts",trust2:"Live beschikbaarheid, transparante directe prijs en veilige betaling via PayPal; PayPal kan ook kaartbetaling aanbieden.",trust3:"Zonder tussenpersoon of extra boekingsplatform.",tile:"Direct boeken",tile2:"Live beschikbaarheid controleren",request:"Boekingsaanvraag sturen",blocked:"⛔ Bezet – kies andere data",blocked2:"De kamer is voor deze data niet beschikbaar.",blocked3:"⛔ Bezet – kies andere data.",checking:"Beschikbaarheid controleren",checking2:"De beschikbaarheid wordt gecontroleerd met de actuele Booking-kalender …",pay:"Veilig betalen met PayPal",available:"✅ Vrij – veilige rechtstreekse betaling",available2:"De data zijn volgens de actuele Booking-kalender beschikbaar. Voor u naar PayPal gaat, wordt de reservering nogmaals server-side gecontroleerd. PayPal kan in de gastcheckout kaartbetaling aanbieden.",available3:"✅ Vrij – gecontroleerd met de actuele Booking-kalender.",config:"Direct betalen is momenteel niet volledig beschikbaar. Stuur daarom een boekingsaanvraag.",calendarBlock:"De Booking-kalender blokkeert deze data. Kies andere data.",luggage:"Bagagevervoer heeft een routeafhankelijke prijs. Schakel deze optie uit om nu te betalen, of stuur eerst een aanvraag.",unreachable:"Live beschikbaarheid kan momenteel niet worden gecontroleerd. Stuur een aanvraag of probeer het later opnieuw.",preparing:"PayPal voorbereiden …",finalCheck:"Beschikbaarheid en prijs worden nu een laatste keer op de server gecontroleerd.",paypalError:"⚠️ PayPal kon niet worden gestart"}
    };
    const tx=(key)=>T[checkoutLang]?.[key]||T.en[key]||T.de[key]||key;
    const L=(de,en)=>checkoutLang==="de"?de:(checkoutLang==="en"?en:(en||de));'''

if old not in s:
    raise RuntimeError("language anchor not found")
s = s.replace(old, new, 1)

# Replace the previously bilingual critical surface with native dictionary lookups.
repls = {
'L("Termin wählen","Choose dates")':'tx("choose")',
'L("Direkt buchen ohne Buchungsplattform","Book direct without another booking platform")':'tx("hero")',
'L("Wachau-Etappe direkt buchen","Book your Wachau stay direct")':'tx("title")',
'L("Reisedaten wählen, Live-Verfügbarkeit prüfen und einen freien Termin sicher mit PayPal oder Kredit-/Debitkarte direkt buchen. Falls Sofortbuchung nicht möglich ist, bleibt die persönliche Anfrage verfügbar.","Choose your dates, check live availability and book an available stay securely via PayPal. PayPal may also offer debit or credit card payment. If instant booking is unavailable, you can still send a personal request.")':'tx("intro")',
'L("Direkt buchen bei den Gastgebern","Book directly with your hosts")':'tx("trust")',
'L("Live-Verfügbarkeit, transparenter Preis und sichere Zahlung über PayPal – auch per Kredit- oder Debitkarte, soweit PayPal dies anbietet.","Live availability, transparent direct price and secure payment via PayPal; debit or credit card may also be offered by PayPal.")':'tx("trust2")',
'L("Ohne Provision oder Umweg über eine zusätzliche Buchungsplattform.","No detour through another booking platform.")':'tx("trust3")',
'L("Direkt buchen","Book direct")':'tx("tile")',
'L("Verfügbarkeit live prüfen","Check live availability")':'tx("tile2")',
'L("Direkt buchen – Verfügbarkeit live prüfen","Book direct – check live availability")':'`${tx("tile")} – ${tx("tile2")}`',
'L("Buchungsanfrage senden","Send booking request")':'tx("request")',
'L("⛔ Belegt – bitte anderen Termin wählen","⛔ Unavailable – please choose different dates")':'tx("blocked")',
'L("Das Zimmer ist für diesen Zeitraum bereits belegt.","The room is unavailable for these dates.")':'tx("blocked2")',
'L("⛔ Belegt – bitte einen anderen Termin wählen.","⛔ Unavailable – please choose different dates.")':'tx("blocked3")',
'L("Verfügbarkeit wird geprüft","Checking availability")':'tx("checking")',
'L("Verfügbarkeit wird direkt mit dem aktuellen Booking-Kalender geprüft …","Availability is being checked against the current Booking calendar …")':'tx("checking2")',
'L("Jetzt mit PayPal oder Karte bezahlen","Pay securely with PayPal")':'tx("pay")',
'L("✅ Termin frei – sichere Direktzahlung","✅ Available – secure direct payment")':'tx("available")',
'L("Termin ist laut aktuellem Booking-Kalender frei. Beim Klick wird der Termin serverseitig reserviert und vor PayPal nochmals sicher geprüft. Eine Kredit-/Debitkartenzahlung kann PayPal im Gast-Checkout anbieten; die tatsächliche Verfügbarkeit bestimmt PayPal.","These dates are available according to the current Booking calendar. When you continue, the stay is held server-side and checked once more before PayPal. PayPal may offer debit or credit card payment in guest checkout; availability is determined by PayPal.")':'tx("available2")',
'L("✅ Frei – live über den aktuellen Booking-Kalender geprüft.","✅ Available – checked live against the current Booking calendar.")':'tx("available3")',
'L("Sofortzahlung ist noch nicht vollständig eingerichtet. Bitte senden Sie stattdessen die Buchungsanfrage.","Instant payment is not fully available right now. Please send a booking request instead.")':'tx("config")',
'L("Der Booking-Kalender sperrt diesen Zeitraum. Bitte einen anderen Termin wählen.","The Booking calendar blocks these dates. Please choose different dates.")':'tx("calendarBlock")',
'L("Gepäcktransport hat einen streckenabhängigen Preis. Bitte Gepäcktransport abwählen und die Übernachtung bezahlen oder zuerst eine Anfrage senden.","Luggage transfer has a route-dependent price. Please deselect it to pay for the stay now, or send a request first.")':'tx("luggage")',
'L("Live-Verfügbarkeitsprüfung derzeit nicht erreichbar. Bitte Buchungsanfrage senden oder später erneut versuchen.","Live availability is temporarily unavailable. Please send a booking request or try again later.")':'tx("unreachable")',
'L("PayPal wird vorbereitet …","Preparing PayPal …")':'tx("preparing")',
'L("Verfügbarkeit und Preis werden jetzt serverseitig final geprüft.","Availability and price are now being checked one final time on the server.")':'tx("finalCheck")',
'L("⚠️ PayPal konnte nicht gestartet werden","⚠️ PayPal could not be started")':'tx("paypalError")',
}
for a,b in repls.items():
    s=s.replace(a,b)

# Dynamic priced CTA was special-cased for de/en; make it native for all languages.
s=s.replace('''? (deCheckout?`Jetzt ${total.toFixed(2).replace(".",",")} EUR mit PayPal oder Karte bezahlen`:`Pay ${total.toFixed(2)} EUR securely with PayPal`)
        : tx("pay");''','''? `${tx("pay")} · ${total.toFixed(2).replace(".", checkoutLang==="de"?",":".")} EUR`
        : tx("pay");''')

p.write_text(s, encoding="utf-8")

# Sanity checks
out=p.read_text(encoding="utf-8")
for lang in ("de","en","cs","sk","hu","pl","nl"):
    assert f"{lang}:{{" in out
for needle in ("const tx=", 'tx("available")', 'tx("paypalError")'):
    assert needle in out
print("Native checkout language validation passed")
